POST http://localhost:8000/users/signup/  HTTP/1.1
content-type: application/json

{"email": "marcusbager14@gmail.com", "password": "password", "password2": "password", "username": "testuser"}


###


POST http://localhost:8000/users/login/  HTTP/1.1
content-type: application/json

{"password": "password", "username": "testuser"}


###


GET http://localhost:8000/users/all/  HTTP/1.1

###

GET http://localhost:8000/tickets/all/  HTTP/1.1

###

GET http://localhost:8000/tickets/5d087900015344a7a884927526c725e9/  HTTP/1.1


###

POST http://localhost:8000/tickets/5d087900015344a7a884927526c725e9/  HTTP/1.1
content-type: application/json

{
    "subject": "Hello World",
    "assignee": null,
    "priority": "low",
    "status": "closed",
    "solution": "This is a test solution"
}
###

GET http://localhost:8000/tickets/search/?query=Hej  HTTP/1.1



###

GET http://localhost:8000/tickets/details/  HTTP/1.1

###

GET http://localhost:8000/tickets/company/74021f12f99a47daa1c39c716498f6bf/  HTTP/1.1


###

PATCH http://localhost:8000/tickets/company/74021f12f99a47daa1c39c716498f6bf/  HTTP/1.1
content-type: application/json

{
    "name": "Instamatch",
    "city": "Odense",
    "address": "ODense vej",
    "email": "info@instamatch.dk",
    "vat_no": "DK12321313",
    "service_level_agreement": {
        "product": "ComputerService",
        "max_response_time": 1,
        "max_resolution_time": 22,
        "is_accepted": true
    }
}




###

GET http://localhost:8000/tickets/companies/  HTTP/1.1


###

GET http://localhost:8000/tickets/my-tickets/  HTTP/1.1



###

POST http://localhost:8000/users/update/  HTTP/1.1
content-type: application/json

{
    "email": "marcusbager@gmail.com",
    "role": "it-supporter",
    "is_active": true,
    "company": [
        "74021f12f99a47daa1c39c716498f6bf"
    ]
}


###

POST http://localhost:8000/tickets/create/  HTTP/1.1
content-type: application/json

{
    "subject": "Test ticket",
    "description": "This is a test ticket",
    "priority": "low",
    "status": "new",
    "level": 1,
    "service_level_agreement": "e69d31ecc8ad4e398b349ed789ac161c"
}

