# Generated by Django 4.2.3 on 2024-08-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0003_ticket_duo_date"),
        ("user", "0002_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="service_level_agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company",
                to="ticket.servicelevelagreement",
            ),
        ),
    ]
