# Generated by Django 4.2.3 on 2024-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ManyToManyField(related_name="users", to="user.company"),
        ),
    ]
