# Generated by Django 4.2.3 on 2024-08-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0013_rename_creaeted_by_knownerror_created_by"),
        ("user", "0006_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="service_level_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company",
                to="ticket.servicelevelagreement",
            ),
        ),
    ]
