# Generated by Django 4.2.3 on 2024-08-21 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0002_servicelevelagreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="duo_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 21, 12, 6, 0, 332115)
            ),
            preserve_default=False,
        ),
    ]
