# Generated by Django 4.2.3 on 2024-08-21 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0003_ticket_duo_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="duo_date",
            new_name="due_date",
        ),
    ]
