# Generated by Django 4.2.3 on 2024-08-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0004_rename_duo_date_ticket_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.TextField(default="hej"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="service_level_agreement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="ticket.servicelevelagreement",
            ),
            preserve_default=False,
        ),
    ]
