# Generated by Django 4.2.3 on 2024-08-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0005_ticket_description_ticket_service_level_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="service_level_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="ticket.servicelevelagreement",
            ),
        ),
    ]
