# Generated by Django 4.2.3 on 2024-08-23 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket", "0006_alter_ticket_service_level_agreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
