# Generated by Django 4.2.3 on 2024-08-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0007_ticket_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=16,
            ),
        ),
    ]
