# Generated by Django 4.2.3 on 2024-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0008_alter_ticket_priority_alter_ticket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicelevelagreement",
            name="max_respnse_time",
        ),
        migrations.AddField(
            model_name="servicelevelagreement",
            name="max_response_time",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="servicelevelagreement",
            name="max_resolution_time",
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
