# Generated by Django 4.2.3 on 2024-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0009_remove_servicelevelagreement_max_respnse_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="due_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
