# Generated by Django 4.2.3 on 2024-08-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0010_alter_ticket_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="solution",
            field=models.TextField(blank=True, null=True),
        ),
    ]
