# Generated by Django 4.2.3 on 2024-08-28 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0012_knownerror"),
    ]

    operations = [
        migrations.RenameField(
            model_name="knownerror",
            old_name="creaeted_by",
            new_name="created_by",
        ),
    ]
