# Generated by Django 4.2.3 on 2024-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0013_rename_creaeted_by_knownerror_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
